In [2]:
import numpy as np

In [4]:
x = np.array([3,4,9])

In [5]:
y = np.array([4,9,7])

In [6]:
x+y

array([ 7, 13, 16])

In [8]:
x = np.array([[2,3],[4,5]])
x

array([[2, 3],
       [4, 5]])

In [9]:
x.ndim

2

In [10]:
x.dtype

dtype('int64')

In [12]:
np.array([[1,3],[4,5],[1.2,3]]).dtype

dtype('float64')

In [13]:
x.shape

(2, 2)

In [20]:
x = np.array([1,2,3,4])
x.sum()

np.int64(10)

In [21]:
np.sum(x)

np.int64(10)

In [22]:
x = np.array([1,2,3,4,5,6])

In [29]:
#reshape array in 3 rows and 2 columns
x_reshape = x.reshape((3,2)) 
x_reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
x_reshape[0,0]

np.int64(1)

In [32]:
x_reshape[2,1]

np.int64(6)

In [33]:
x_reshape[1,1] = 10
x_reshape

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [34]:
x

array([ 1,  2,  3, 10,  5,  6])

In [36]:
# This shows that if we modify reshape changes can be seen in x too, This implies that x_reshape and x share same memory

In [37]:
# numpy ARRAY have some attribute like shape,ndim and T (Transpose)
x_reshape.shape,x_reshape.ndim,x_reshape.T

((3, 2),
 2,
 array([[ 1,  3,  5],
        [ 2, 10,  6]]))

In [38]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 3.16227766, 2.23606798,
       2.44948974])

In [39]:
#This will square every element in x
x**2

array([  1,   4,   9, 100,  25,  36])

In [41]:
#This will root every element in x
x**0.5

array([1.        , 1.41421356, 1.73205081, 3.16227766, 2.23606798,
       2.44948974])

In [48]:
# random in numpy
# loc = mean
# scale = standard deviation
x = np.random.normal(size=50)
x

array([-0.08752818, -0.5323547 ,  0.05214906,  0.37538414, -0.70187721,
        0.49038601, -1.21577515,  0.41096121,  0.43991359,  0.77909553,
        0.21613608, -0.56074541, -1.30162725, -0.50690812,  0.48471844,
        1.65193798, -0.64790009,  0.6118022 ,  0.08713572, -0.08432181,
        0.74587786, -0.08285243, -0.86962378, -0.06718432,  1.34497689,
       -0.30584855, -1.35240395,  0.94605189, -0.13273674,  0.63650223,
       -0.34131134, -0.14538122, -1.07715331,  0.08996706, -0.2543839 ,
       -0.58152083, -0.92722036, -0.09375618, -0.87160065, -1.72994683,
        0.43044197, -0.41155112,  0.46221514,  0.20155791,  0.73782175,
        0.99700454,  2.91171679,  0.96866408, -1.47124374,  0.50131521])

In [49]:
y = x + np.random.normal(loc=50,scale=1,size=50)

In [51]:
# This will compute correlation between x and y
np.corrcoef(x,y)

array([[1.        , 0.75324417],
       [0.75324417, 1.        ]])

In [52]:
rng = np.random.default_rng(1303)

In [53]:
rng.normal(scale=5,size=2)

array([ 4.09482632, -1.07485605])

In [55]:
rng2 = np.random.default_rng(1303)

In [60]:
rng2.normal(scale=5,size=2)

array([ 4.09482632, -1.07485605])

In [62]:
#other methods of an array in numpy
#mean : mean()
#var : variane()
#standard deviation : std()


In [63]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y),y.mean()

(np.float64(-0.1126795190952861), np.float64(-0.1126795190952861))

In [68]:
#checking with random variable
n = np.random.normal(size=10,loc=10,scale=10)
n.mean(),n.std()

(np.float64(16.327141902903307), np.float64(9.439275155911796))

In [75]:
# variance = (y-mean(y))**2
np.var(y),y.var(),np.mean((y-y.mean())**2)

(np.float64(2.7243406406465125),
 np.float64(2.7243406406465125),
 np.float64(2.7243406406465125))

In [76]:
np.sqrt(np.var(y)),np.std(y)

(np.float64(1.6505576756498128), np.float64(1.6505576756498128))

In [77]:
X = rng.standard_normal((10,3))

In [78]:
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])